/** Mapping of screenshot gallery UI element IDs to their resolved asset URLs. */
export const uiMap = {
  "counter01": new URL("./images/ui/01.gif", import.meta.url).href,
  "counter02": new URL("./images/ui/02.gif", import.meta.url).href,
  "counter03": new URL("./images/ui/03.gif", import.meta.url).href,
  "counter04": new URL("./images/ui/04.gif", import.meta.url).href,
  "counter05": new URL("./images/ui/05.gif", import.meta.url).href,
  "counter06": new URL("./images/ui/06.gif", import.meta.url).href,
  "counter07": new URL("./images/ui/07.gif", import.meta.url).href,
  "counter08": new URL("./images/ui/08.gif", import.meta.url).href,
  "counter09": new URL("./images/ui/09.gif", import.meta.url).href,
  "counter10": new URL("./images/ui/10.gif", import.meta.url).href,
  "counter11": new URL("./images/ui/11.gif", import.meta.url).href,
  "counter12": new URL("./images/ui/12.gif", import.meta.url).href,
  "arrow_down": new URL("./images/ui/arrow_down.gif", import.meta.url).href,
  "arrow_up": new URL("./images/ui/arrow_up.gif", import.meta.url).href,
  "img": new URL("./images/ui/img.gif", import.meta.url).href,
  "ltab_off": new URL("./images/ui/ltab_off.gif", import.meta.url).href,
  "ltab_on": new URL("./images/ui/ltab_on.gif", import.meta.url).href,
  "menu_off": new URL("./images/ui/menu_off.gif", import.meta.url).href,
  "menu_on": new URL("./images/ui/menu_on.gif", import.meta.url).href,
  "next": new URL("./images/ui/next.gif", import.meta.url).href,
  "of": new URL("./images/ui/of.gif", import.meta.url).href,
  "prev": new URL("./images/ui/prev.gif", import.meta.url).href,
  "rtab_off": new URL("./images/ui/rtab_off.gif", import.meta.url).href,
  "rtab_on": new URL("./images/ui/rtab_on.gif", import.meta.url).href,
};
